### ISSUE TITLE
Resume on Leia

### ISSUE THREAD

**Issue by host505** [therealatreides/houseatreides#1]
Hey, I saw you've implemented the resume Leia fix I used on my 'fork', but it still won't work like that: on 18 you should use onAVStarted() instead, for resume to work.
So you need both functions for 18 and older versions to work:
https://github.com/host505/plugin.video.theoath/blob/master/resources/lib/modules/player.py#L256-L270
Ps thanks for all you do/have done, btw.

**Comment by therealatreides** [comment]
Thanks for pointing out mate, greatly appreciate the heads up. Will be updated in the next version.

Again, thx for the heads up. Much appreciated.
